# Header
menu:
  Home: /
  About: /about/
  Contact: /about/#Contact_Me
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- ad
- recent_posts
- category
- tagcloud
- archive
- tag

# Miscellaneous
google_analytics: UA-10568795-1
favicon: /favicon.png
twitter: minhajuddin
google_plus: +KhajaMinhajuddin
fb_admins:
fb_app_id:
